### ISSUE TITLE
[Bug] There is a bug in the auto-update feature.

### ISSUE THREAD

**Issue by Accademia** [viarotel-org/escrcpy#317]
The software appears to check whether the macOS device is located in China. If it detects the device is in China, it prompts the user to use a VPN to download updates but does not automatically initiate the update package download. This logic is flawed because many users in China can still access GitHub (via a VPN). In such cases, the update package should be downloaded automatically.

**Comment by viarotel** [comment]
I tried to solve this problem and finally found that it was caused by the unsigned software package (due to system security policy, the installation package will be automatically cleared by the operating system after downloading). Software signing requires applying for a developer account and paying an annual fee. At present, the application is completely powered by love and does not have sufficient financial support for the time being, so if the built-in update fails, please manually download the installation package to update.
